// Builds dist/worker.js: one self-contained ES module (no bundler dependency) for Workers dashboard/API upload.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';

const types = { html: 'text/html; charset=utf-8', css: 'text/css; charset=utf-8', js: 'text/javascript; charset=utf-8' };
const assets = {};
for (const f of readdirSync('public')) assets['/' + f] = { type: types[f.split('.').pop()] || 'application/octet-stream', body: readFileSync('public/' + f, 'utf8') };
const strip = (src) => src.replace(/^import[\s\S]*?from\s+['"][^'"]+['"];\s*$/gm, '').replace(/^export\s+(?=(async\s+)?(function|const|let|class))/gm, '');
const out = [
  '// Aegisly — generated by build.mjs. Source: src/core.js, src/api.js, src/worker.js, public/*',
  strip(readFileSync('src/core.js', 'utf8')),
  strip(readFileSync('src/api.js', 'utf8')),
  `const ASSETS = ${JSON.stringify(assets)};`,
  strip(readFileSync('src/worker.js', 'utf8')),
].join('\n');
mkdirSync('dist', { recursive: true });
writeFileSync('dist/worker.js', out);
console.log('dist/worker.js', out.length, 'bytes');
